# Generated by Django 4.0.4 on 2022-05-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0005_nurse_is_day_shift_nurse_patients'),
        ('patient', '0002_remove_patient_city_remove_patient_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nurses',
        ),
        migrations.AddField(
            model_name='patient',
            name='is_treated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TreatmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
