# Generated by Django 4.0.4 on 2022-04-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_alter_bed_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
