# Generated by Django 4.0.4 on 2022-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_nurse_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='country',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='state',
        ),
        migrations.AddField(
            model_name='nurse',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='age',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=10, null=True),
        ),
    ]
