# Generated by Django 4.0.4 on 2022-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_remove_patient_city_remove_patient_country_and_more'),
        ('nurse', '0004_remove_nurse_city_remove_nurse_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='is_day_shift',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='patients',
            field=models.ManyToManyField(blank=True, to='patient.patient'),
        ),
    ]
