# Generated by Django 4.0.4 on 2022-05-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0005_nurse_is_day_shift_nurse_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
