# Generated by Django 4.0.4 on 2022-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0006_delete_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='floor_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='room_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
