# Generated by Django 4.0.4 on 2022-05-31 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0007_bed_floor_no_bed_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
