# Generated by Django 4.0.4 on 2022-05-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_doctor_city_remove_doctor_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='treatment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
