# Generated by Django 4.0.4 on 2022-05-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_rename_time_treatment_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='treatment',
            new_name='treatment_value',
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_type',
            field=models.CharField(blank=True, choices=[('Temperature', 'Temperature')], max_length=50, null=True),
        ),
    ]
