# Generated by Django 4.0.4 on 2022-05-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_rename_treatment_treatment_treatment_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
