# Generated by Django 4.0.4 on 2022-05-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_remove_patient_nurses_patient_is_treated_and_more'),
        ('nurse', '0007_bed_floor_no_bed_room_no'),
        ('doctor', '0006_doctor_working_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_type',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='treatment_value',
        ),
        migrations.AddField(
            model_name='treatment',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment',
            field=models.CharField(blank=True, choices=[('Temperature', 'Temperature'), ('Blood Pressure', 'Blood Pressure'), ('Pulse', 'Pulse'), ('Respiration', 'Respiration'), ('Weight', 'Weight'), ('Height', 'Height'), ('BMI', 'BMI'), ('Others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('oxygen_level', models.CharField(blank=True, max_length=20, null=True)),
                ('heart_rate', models.CharField(blank=True, max_length=20, null=True)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
